[package]
name = "agent-os-desktop"
version = "0.1.0-alpha.1"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"

[dependencies]
seven-sixteen-ui = { git = "https://github.com/716-Ventures/716-ui", tag = "v0.1.0-alpha.20", features=["terminal"] }
serde_json = "1"
base64 = "=0.22.1"
libc = "0.2"
gdk4-wayland = "=0.9.6"

[profile.dev]
debug = 0
